import 'normalize.css';
import './style.css';

import { LinkedList, Node } from './app-components';

const linkedListTest = new LinkedList();
console.log(linkedListTest);
console.log(new Node());
console.log(linkedListTest.size());
console.log(linkedListTest.at(0));
console.log(linkedListTest.append(1));
console.log(linkedListTest.headNode);
console.log(linkedListTest.tailNode);
console.log(linkedListTest.list);
console.log(linkedListTest.append(2));
console.log(linkedListTest.headNode);
console.log(linkedListTest.list);
console.log(linkedListTest.tailNode);
console.log(linkedListTest.append(3));
console.log(linkedListTest.headNode);
console.log(linkedListTest.list);
console.log(linkedListTest.tailNode);
console.log(linkedListTest.append(4));
console.log(linkedListTest.at(2));
console.log(linkedListTest.headNode);
console.log(linkedListTest.list);
console.log(linkedListTest.tailNode);
console.log(linkedListTest.size());
console.log(linkedListTest.prepend(-1));
console.log(linkedListTest.headNode);
console.log(linkedListTest.list);
console.log(linkedListTest.tailNode);
console.log(linkedListTest.prepend(-2));
console.log(linkedListTest.headNode);
console.log(linkedListTest.list);
console.log(linkedListTest.tailNode);
console.log(linkedListTest.prepend(-3));
console.log(linkedListTest.headNode);
console.log(linkedListTest.list);
console.log(linkedListTest.tailNode);
console.log(linkedListTest.at(2));
console.log(linkedListTest.prepend(-4));
console.log(linkedListTest.headNode);
console.log(linkedListTest.list);
console.log(linkedListTest.tailNode);
console.log(linkedListTest.size());
console.log(linkedListTest.head());
console.log(linkedListTest.tail());
console.log(linkedListTest.at(8));
console.log(linkedListTest.at(56));
console.log(linkedListTest.list);
console.log(linkedListTest.pop());
console.log(linkedListTest.tailNode);
console.log(linkedListTest.list);
